"""Tablas who

Revision ID: 32db601317a5
Revises: 
Create Date: 2023-05-01 00:43:24.795693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32db601317a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xxart_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ovn', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xxart_user', schema=None) as batch_op:
        batch_op.drop_column('ovn')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_by')
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
